# Generated by Django 2.2 on 2020-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseName',
            new_name='course_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
